Vizzuality/gfw-climate

app/controllers/api/v1/countries_controller.rb, app/controllers/countries_controller.rb, app/controllers/posts_controller.rb, app/models/concerns/cached.rb, app/models/country.rb, app/models/jurisdiction.rb, app/models/post.rb, app/views/api/v1/countries/show_jurisdiction.json.rabl, app/views/countries/show.html.slim, app/views/posts/index.html.slim, config/routes.rb, doc/api/countries/getting_a_list_of_enabled_countries.json, doc/api/countries/getting_a_specific_country.json, doc/api/countries/getting_a_specific_jurisdiction.json, doc/api/index.json, spec/acceptance/api/v1/countries_spec.rb, spec/controllers/countries_controller_spec.rb, spec/controllers/posts_controller_spec.rb, spec/models/jurisdiction_spec.rb
Get '/countries/aus/5' with UMD. Provisionally end-point
=> Endpoint for regions - jurisdictions

app/assets/javascripts/compare.js, app/assets/stylesheets/compare.scss, app/controllers/compare_controller.rb, app/controllers/countries_controller.rb, app/views/compare/index.html.slim, app/views/layouts/compare.html.slim, app/views/shared/_navbar2_landing.html.erb, config/initializers/assets.rb, config/routes.rb, spec/controllers/compare_controller_spec.rb, spec/controllers/countries_controller_spec.rb
Compare was part of countries. We decided to make an independent structure for each section...  
router.js is a dummy example copied from countries router just to make it works. 
also test added. Please verify.
=> Compare. Independent structure

app/assets/javascripts/compare.js, app/assets/javascripts/compare/presenters/CompareSelectorsPresenter.js, app/assets/javascripts/compare/presenters/PresenterClass.js, app/assets/javascripts/compare/router.js, app/assets/javascripts/compare/services/PlaceService.js, app/assets/javascripts/compare/views/index/CompareSelectorsView.js, app/assets/javascripts/services/PlaceService.js, app/assets/stylesheets/_mixins.scss, app/assets/stylesheets/_states.scss, app/views/compare/index.html.slim
There are two console.log, please, don't delete, they are for the next step.
=> Place service implemented. 

app/assets/javascripts/widgets/indicators/line/LineChart.js, app/assets/javascripts/widgets/indicators/line/LineChartIndicator.js, app/assets/javascripts/widgets/presenters/TabPresenter.js, app/assets/javascripts/widgets/templates/tab.handlebars, app/assets/javascripts/widgets/views/TabView.js
Years selector trigger updates on url and graphs
=> Years selector trigger updates on url and graphs

app/assets/javascripts/countries/presenters/show/WidgetGridPresenter.js
=> Enabled piecharts in country show page

app/views/home/index.html.slim
=> Text change

app/assets/javascripts/map/helpers/layersHelper.js, app/assets/javascripts/map/templates/layersNav.handlebars, app/assets/javascripts/map/views/layers/BiomassLossLayer.js, app/assets/javascripts/map/views/layers/CarbonStocksLayer.js
=> Fake layers, will change to biomass and carbon stock

app/assets/javascripts/countries/templates/reports-modal.handlebars
Report panel options changed following: https://basecamp.com/1756858/projects/9386799/todos/214795894 
Some of the items she refer to weren't there...I did my best. :P
=> customize report menu names changed. 

app/assets/stylesheets/modules/_select.scss
Added a small arrow next to "biomass" to indicate there are other options
pivotal id: #107818302.
https://basecamp.com/1756858/projects/9386799/todos/216944345
=> arrow to show there are more options

app/assets/stylesheets/_header.scss, app/assets/stylesheets/layouts/_map.scss, app/views/layouts/application.html.slim, app/views/shared/_navbar2_landing.html.erb
Tabs reordered after comments at: 
https://basecamp.com/1756858/projects/9386799/todos/216943450
I directly got ride of "Data and Methods" subsection and add all it items to "About".
I also change site title tag to   #{@title} | Global Forest Watch - Climate
DON'T MERGE BY NOW. There is a contradiction between two BC TODO's.
+++++++++++ READY TO GO, GO, GO ++++++++++++
=> menu tabs reordered pivId: #107806318

app/assets/javascripts/countries/presenters/show/CountryModalPresenter.js, app/assets/javascripts/countries/templates/reports-modal.handlebars, app/assets/javascripts/countries/views/show/CountryModalView.js, app/assets/javascripts/countries/views/show/reports/AreasView.js, spec/models/indicator_spec.rb
Fixed selected indicators for national tab when this on doesn't receive any options.
=> Fixed defaults selectors on national tab

app/views/shared/_navbar2_landing.html.erb
Added actions to enable highlight navbar when the user is in index (/countries) and show (/countries/BRA).
=> Fixed current navbar position

app/views/home/index.html.slim
PT: https://www.pivotaltracker.com/story/show/108529088
=> explore map button disabled not deleted.

app/assets/javascripts/home/views/sliderView.js, app/assets/stylesheets/layouts/_application.scss, app/assets/stylesheets/modules/home/_features-slider.scss, app/views/home/index.html.slim, app/views/shared/_sources_landing.html.slim
New text.
Manage sliders with buttons. 
At the beginning, we wanted 4 different sliders for each profession. As the client has only send content for only one slide on each, we have simplify it to have a more simple slider that can be manage with buttons at bottom.
=> Slider at the bottom updated.

app/views/home/index.html.slim
At least, but not last!!! Tada!!!! 
Data download link.
=> added link download data at home page.

app/assets/javascripts/countries/views/CountryPantropicalView.js, app/views/countries/pantropical.html.slim
It needs some styling yet but we're good to go, you can play with it.
=> Feature/play pause pantropical years  :movie_camera: 

app/views/shared/_sources_map.html.erb
=> added infobuble for biomass loss

app/assets/javascripts/map/templates/tabs/countries.handlebars
Reverts Vizzuality/gfw-climate#173
=> Revert "Analysis reverted. There are many many issues here. We need to develo…"

app/assets/javascripts/countries/presenters/show/CountryWidgetsModalPresenter.js, app/assets/javascripts/countries/templates/countryWidgetsModal.handlebars, app/assets/javascripts/countries/views/show/WidgetGridView.js, app/assets/stylesheets/modules/countries/_m-country-modal.scss, app/assets/stylesheets/modules/countries/_no-indicators.scss
You CAN merge this PR already :) @simaob 
- Added inner modal styles :heavy_check_mark:
- Align properly no-indicators template:heavy_check_mark:
- Take a look to strange behavior on modal :heavy_check_mark:
- Improved toggle warnings when user select a non-valid selection and other cases :heavy_check_mark:
=> Country modals

app/assets/javascripts/countries/views/pantropical/vis.js, app/assets/javascripts/embed/views/pantropical/vis.js, app/assets/stylesheets/modules/_select.scss, app/assets/stylesheets/modules/embed/_pantropical.scss, app/assets/stylesheets/modules/map/_country-select.scss, app/assets/stylesheets/modules/pantropical/_m-pantropical.scss, app/views/countries/pantropical.html.slim, spec/controllers/countries_controller_spec.rb
=> Feature/amendments on pantropical - WIP -

app/assets/javascripts/countries/views/CountryPantropicalView.js, app/assets/javascripts/embed/PantropicalView.js
I have reduced the player speed from 1.5s to 0.75s. Let me know if this is the desired result or if we should change something more. Thanks!
=> Reduced speed to the half

app/assets/stylesheets/modules/widgets/_widget.scss
Pending on what Sergio says about this on PV: https://www.pivotaltracker.com/story/show/109524766
=> Undo style

app/assets/javascripts/map/templates/layersNav.handlebars, app/views/shared/_sources_map.html.erb
Remember to clear localStorage to see legend changes
=> Land use menu fixes

app/assets/javascripts/widgets/templates/widget.handlebars, app/assets/stylesheets/modules/widgets/_widget.scss
Info button blue and no literal "read more"
=> info btn blue

app/assets/javascripts/widgets/indicators/multiline/MultiLineChartIndicator.js
- Wrong data being set when toggling between tabs.
- Added missing methods when removing the view.
=> Fix: Subnational data - Issue with widget 

app/assets/javascripts/countries/views/show/WidgetGridView.js, app/assets/javascripts/countries/views/show/reports/AreasView.js, app/assets/javascripts/countries/views/show/reports/NationalView.js, app/assets/javascripts/countries/views/show/reports/SubNationalView.js
- Right now previous widgets were kept in memory and it was causing multiple tooltips and other issues under these tabs, this PR solves that.
=> Feat: Countries - Remove previous widgets before creating a new instance

app/assets/stylesheets/modules/_modal.scss, app/assets/stylesheets/modules/_modal_new.scss, app/assets/stylesheets/modules/common/_m-modal-fields.scss, app/assets/stylesheets/modules/widgets/_widget.scss
- Solves the issue with Firefox v.44 and posible other browsers.
=> Fix - Widgets - SVG icons

app/assets/javascripts/views/SidebarNavView.js, app/assets/stylesheets/layouts/_application.scss, app/assets/stylesheets/modules/embed/_pantropical.scss, app/assets/stylesheets/modules/pantropical/_m-pantropical.scss, app/views/countries/pantropical.html.slim, app/views/static/about.html.erb
New tab tutrials and videos. 
New tab publications and link form pantropical to Zarin report.
=> about page new tabs. 

app/assets/javascripts/map/presenters/tabs/AnalysisPresenter.js, app/assets/javascripts/map/presenters/tabs/CountriesPresenter.js, app/assets/javascripts/map/views/tabs/AnalysisView.js
Show always the country geom regardless of the tab and keep it selected with or without layers.
=> Feat: Map - Show always the country geom regardless of the tab

app/assets/javascripts/map/services/PlaceService.js, app/assets/javascripts/map/templates/tabs/basemaps.handlebars, app/assets/javascripts/map/views/MapView.js, app/assets/javascripts/map/views/maptypes/basemapStyles.js, app/assets/stylesheets/layouts/_map.scss
- Set dark matter as the default basemap.
- Added a background color for each basemap.
=> Feat: Basemap - Set dark matter as default

app/views/layouts/application.html.slim, app/views/layouts/compare.html.slim, app/views/layouts/countries.html.slim, app/views/layouts/map.html.slim, app/views/layouts/static.html.slim
Updated version to test on staging.
=> Feat: GFW Assets - Updated version (nightly)

app/assets/stylesheets/modules/home/_features.scss, app/views/home/index.html.slim
- Moved "Monitor progress" slide before "Compare countries"
=> Feat: Home - Move monitor progress slide before compare

app/assets/stylesheets/modules/static/_publications.scss, app/views/shared/_navbar2_landing.html.erb, app/views/static/about.html.erb
- Added link to GFW Climate blogs under Publications.
- Removed blogs links from the main navigation bar.
=> Feat: About - Added blogs links under publications 

app/assets/javascripts/map/templates/legend/legend.handlebars
- This will use the correct ID for the metadata API.
=> Feat: Legend - Use source_json for the info windows

app/assets/stylesheets/_base.scss
Added default styles for sub and sup HTML tags ->
=> Feat: Added sub / sup tag styles

app/assets/javascripts/map/presenters/analysis/AnalysisResultsPresenter.js, app/assets/javascripts/map/templates/analysis/analysisResultsChart.handlebars, app/assets/javascripts/widgets/templates/indicators/bars/barschart-legend.handlebars, app/assets/stylesheets/modules/map/_analisys-graph.scss, app/assets/stylesheets/modules/map/_tab-analysis.scss
New data added:
- Average of the aboveground live biomass
- Average of carbon stored in aboveground live biomass
=> Feat: Analysis - Average of the aboveground live biomass 

README.md, app/assets/javascripts/insights/templates/insights-glad-alerts-tooltip.handlebars, app/assets/javascripts/insights/views/InsightsGladAlertsChartView.js, app/assets/javascripts/insights/views/InsightsGladAlertsView.js, app/assets/stylesheets/modules/insights/_m-glad-vis.scss, app/views/layouts/compare.html.slim, app/views/layouts/countries.html.slim, app/views/layouts/embed.html.slim, app/views/layouts/map.html.slim
- Loads the Glad alerts images, if it doesn't exists it shows a message.
=> Feat: Insights - Glad alerts - Image loading

app/assets/javascripts/helpers/geojsonUtilsHelper.js, app/assets/javascripts/map/presenters/MapPresenter.js, app/assets/javascripts/map/presenters/tabs/AnalysisPresenter.js, app/assets/javascripts/map/services/GeostoreService.js, app/assets/javascripts/map/services/PlaceService.js, app/assets/javascripts/map/services/ShapefileService.js, app/assets/javascripts/map/templates/tabs/analysis.handlebars, app/assets/javascripts/map/views/GeoStylingView.js, app/assets/javascripts/map/views/tabs/AnalysisShapeUploadView.js, app/assets/javascripts/map/views/tabs/AnalysisView.js, app/assets/stylesheets/modules/map/_module-tabs.scss, app/assets/stylesheets/modules/map/_tab-analysis.scss, app/views/shared/_sources_map.html.erb, bower.json
Added feature to upload shapes to analyze data.
=> Feat: Map - Analysis - Shape upload as in GFW

app/assets/javascripts/helpers/geojsonUtilsHelper.js, app/assets/javascripts/map/presenters/analysis/AnalysisResultsPresenter.js, app/assets/javascripts/map/presenters/tabs/AnalysisPresenter.js, app/assets/javascripts/map/services/AnalysisService.js, app/assets/javascripts/map/services/GeostoreService.js, app/assets/javascripts/map/templates/analysis/analysisResults.handlebars, app/assets/javascripts/map/views/analysis/AnalysisResultsView.js, app/assets/javascripts/widgets/indicators/bars/BarChart.js, app/views/layouts/map.html.slim
- Analysis now uses the new API, including geostore handleling
- New ENV variable:
`GFW_API_HOST_V2`
=> Feat: Analysis with API 2.0

app/assets/javascripts/map/templates/legend/mangrove_biomass.handlebars
=> tag close deleted

app/assets/javascripts/insights/templates/insights-glad-alerts-legend.handlebars, app/assets/javascripts/insights/templates/insights-glad-alerts-tooltip.handlebars, app/assets/javascripts/insights/templates/insights-glad-alerts.handlebars, app/assets/javascripts/insights/views/InsightsGladAlertsChartView.js, app/assets/javascripts/insights/views/InsightsGladAlertsView.js, app/assets/stylesheets/modules/insights/_m-chart-glad.scss, app/assets/stylesheets/modules/insights/_m-glad-vis.scss, app/views/layouts/countries.html.slim, app/views/shared/_sources_widgets.html.erb
- Added new labels in the graph and removed some from the legend.
- Now the data is loaded from the new API (datasets will change soon, it'll be just an ID change).
- Metadata added.
- Text changes.
=> Insights - Glad Alerts Visualization UI tweaks and data from API

app/assets/javascripts/map/templates/infowindow.handlebars, app/assets/javascripts/map/views/layers/MangroveBiomassLayer.js, app/assets/stylesheets/modules/map/_infowindow.scss
- Removed the analysis feature and added information for this layer's (Aboveground Mangrove Biomass Density) info window.
=> Feat: Map - Layer - Mangrove Biomass - Info window data

app/assets/javascripts/insights/views/InsightsGladAlertsView.js
The API changed the format for the responses, now it supports the new one.
=> Feat: Insights - GLAD visualization - new response format

app/assets/javascripts/insights/templates/insights-glad-alerts-legend.handlebars, app/assets/javascripts/insights/templates/insights-glad-alerts.handlebars, app/assets/javascripts/insights/views/InsightsGladAlertsChartView.js, app/assets/javascripts/insights/views/InsightsGladAlertsView.js, app/assets/stylesheets/modules/insights/_m-chart-glad.scss, app/assets/stylesheets/modules/insights/_m-glad-vis.scss, app/assets/stylesheets/modules/insights/_m-insights.scss
Changes:
- Added the full year.
- Embed and mobile styles.
- Small UI tweaks.
=> Feat: Insights - Glad - Final tweaks, responsive and full year in chart

README.md, app/assets/javascripts/insights/templates/insights-glad-alerts-legend.handlebars, app/assets/javascripts/insights/views/InsightsGladAlertsView.js, app/views/layouts/compare.html.slim, app/views/layouts/countries.html.slim, app/views/layouts/embed.html.slim, app/views/layouts/map.html.slim
Changes:
- Added GFW's url by an ENV variable.
Don't forget to add the **new** environment variable:
`GFW_URL=http://www.globalforestwatch.org`
=> Feat: Insights - GLAD - Map url by ENV variable

app/assets/javascripts/insights/views/InsightsGladAlertsChartView.js
Fix for Brazil's label <- To be connected to the dataset
=> Fix: Insights - GLAD - Label for Brazil

app/assets/javascripts/insights/views/InsightsGladAlertsChartView.js
- Labels fixed for the Y axis.
=> Fix: Insights - Glad - Removed Y label padding

app/assets/javascripts/map/templates/legend/hsdw.handlebars, app/assets/javascripts/map/views/LegendView.js
Added missing Soil organic carbon legend
=> Feat: Legend - Soil organic carbon

app/assets/javascripts/insights/views/InsightsGladAlertsView.js
Now the query supports an aggregation by multiple state ISO for cases like Kalimantan.
=> Feat: Insights - GLAD - Aggregation by state iso

app/assets/javascripts/map/services/AnalysisService.js, app/assets/javascripts/map/services/GeostoreService.js
Use the same host for all services
=> Update env host

app/views/layouts/countries.html.slim, app/views/layouts/embed.html.slim, app/views/layouts/map.html.slim
I forgot to add the env to the global scope.
=> Add env in global scope

app/assets/javascripts/map/presenters/tabs/AnalysisPresenter.js
Sorry, this is the last one... wrong variable names to layerSlug instead of useid.
=> Fix wrong variable name

app/assets/javascripts/insights/views/InsightsGladAlertsChartView.js, app/assets/stylesheets/modules/insights/_m-chart-glad.scss
Add literal explanation for the state of kalimantan.
=> Add literal for kalimantan explanation

app/assets/javascripts/countries/templates/countryReport.handlebars, app/assets/javascripts/countries/templates/report/pie-chart.handlebars, app/assets/javascripts/countries/views/CountryReportView.js, app/assets/javascripts/countries/views/report/HistoricalTrendChartView.js, app/assets/javascripts/countries/views/report/PieChartView.js, app/assets/javascripts/countries/views/report/SummaryChartView.js, app/assets/stylesheets/countries.scss, app/assets/stylesheets/modules/countries/_report.scss, app/assets/stylesheets/modules/countries/report/_pie-chart.scss, app/models/country_report.rb
- Removed decimals.
- Change of some texts.
- New pie charts for Historical loss by province and C stocks:
=> Feat: Countries - Report - Pie charts + Fixes

app/assets/stylesheets/modules/countries/_header-show.scss, app/assets/stylesheets/modules/countries/_header-stats.scss
Add responsive for header stats.
=> Add responsive for header stats

app/assets/javascripts/countries/templates/countryReport.handlebars, app/assets/javascripts/countries/views/CountryReportView.js, app/assets/javascripts/countries/views/report/HistoricalTrendChartView.js, app/assets/javascripts/countries/views/report/SummaryChartView.js, app/assets/stylesheets/modules/countries/_report.scss, app/assets/stylesheets/modules/countries/report/_historical-trend-chart.scss
- Includes new chart: Forest-related emissions.
- Added new blocks of text (pending to update with real ones).
- Change of the previous Historical Trend chart:
=> Feature: Countries -  Report: Forest related emissions chart

app/assets/javascripts/countries/templates/countryReport.handlebars, app/assets/javascripts/countries/views/CountryReportView.js, app/assets/javascripts/countries/views/report/SliderView.js, app/assets/stylesheets/modules/countries/_report.scss, bower.json, config/requirejs.yml
Add library to sliders 
wip: the report scope and boundaries
=> Add ouslider

app/assets/javascripts/countries/views/report/HistoricalTrendChartView.js
Added missing deviation data in Historical chart
=> Feature: Countries - Report - Deviation data

app/assets/javascripts/insights/views/InsightsGladAlertsView.js
- Change of dataset ID
- Change of name scheme for loss to -> loss_ha
=> Fix: Insights - Glad Alerts Viz - Name scheme change and dataset ID

app/assets/javascripts/countries/views/CountryReportView.js, app/assets/javascripts/countries/views/report/HistoricalTrendChartView.js
- Fix: Deviation calculation.
- Column name change.
=> Fix: Countries - Report - Deviation calculation fix

app/assets/javascripts/countries/templates/countryReport.handlebars, app/assets/javascripts/countries/views/CountryReportView.js, app/assets/javascripts/countries/views/report/ProvincesTopChartView.js
- Layout changes requested by the client.
- Added custom label and support for underscript tags.
=> Fix: Countries - Report - Feedback changes, layout and labels

app/assets/javascripts/countries/templates/countryReport.handlebars, app/assets/javascripts/countries/views/CountryReportView.js, app/assets/stylesheets/countries.scss, app/assets/stylesheets/modules/_slider.scss, app/assets/stylesheets/modules/countries/_report.scss, app/assets/stylesheets/modules/countries/report/_year-selector.scss
- General fixes.
- Year selector:
=> Feature: Countries - Report - Year selector

app/assets/javascripts/countries/templates/countryReport.handlebars, app/assets/javascripts/countries/templates/report/country-geo.handlebars, app/assets/javascripts/countries/views/CountryReportView.js, app/assets/javascripts/countries/views/report/CountryGeoView.js, app/views/layouts/countries.html.slim
- Added first implementation of the geo by @j8seangel
=> Feature: Countries - Report - Geo

app/assets/javascripts/countries/templates/countryReport.handlebars, app/assets/javascripts/countries/templates/report/country-geo.handlebars, app/assets/javascripts/countries/views/CountryReportView.js, app/assets/javascripts/countries/views/report/CountryGeoView.js, app/assets/javascripts/helpers/CountryHelper.js, app/assets/stylesheets/countries.scss, app/assets/stylesheets/modules/countries/_report.scss, app/assets/stylesheets/modules/countries/report/_geo-chart.scss
- Layout tweaks.
- Scope and boundaries section:
=> Feat: Countries - Report - Scope and boundaries

app/assets/javascripts/countries/templates/countryReport.handlebars, app/assets/javascripts/countries/views/CountryReportView.js, app/assets/stylesheets/countries.scss, app/assets/stylesheets/modules/countries/_report.scss, app/assets/stylesheets/modules/countries/report/_print.scss
- Text revisions.
- Print layout setup
=> Feat: Countries - Report - Text revisions and print layout setup

app/assets/javascripts/widgets/indicators/number/NumberChartIndicator.js
Show no data in this indicator because of the broken data.
=> No data on papua emissions drainage

app/views/shared/_sources_widgets.html.erb
as requested in the following BC thread:
https://basecamp.com/1756858/projects/9386799/todos/274672941
Error was in: http://climate.globalforestwatch.org/countries/COD/national?options=eyJ3aWRnZXRzIjp7IkNPRCI6eyIxMSI6W3siaWQiOjExLCJ0YWJzIjp7InR5cGUiOiJsaXN0IiwicG9zaXRpb24iOjEsInVuaXQiOm51bGwsInN0YXJ0X2RhdGUiOm51bGwsImVuZF9kYXRlIjpudWxsLCJ0aHJlc2giOjAsInNlY3Rpb24iOm51bGwsInRlbXBsYXRlIjpudWxsfSwiaW5kaWNhdG9ycyI6WzQwXX1dfX0sImFjdGl2ZVdpZGdldHMiOlsiMTEiXSwidmlldyI6Im5hdGlvbmFsIn0=
=> Fixes info bubble text for one of the indicators

app/models/widget.rb, config/json/widgets.json
=> Adds a fake indicator to support a feature that is not possible at the moment

README.md, app/assets/javascripts/insights/views/InsightsGladAlertsView.js, app/views/layouts/countries.html.slim
=> Fix: Insights - Glad query

app/assets/javascripts/insights/views/InsightsGladAlertsChartView.js, app/assets/javascripts/insights/views/InsightsGladAlertsView.js
=> Feat: Insights - GLAD - Legend and fixes

app/assets/javascripts/map/templates/legend/carbon_gain.handlebars, app/assets/javascripts/map/views/LegendView.js, app/assets/stylesheets/modules/map/_module-legend.scss
Add basic legend for the carbon gain layers:
=> Add carbon gain layers legend

app/assets/javascripts/countries/presenters/show/CountryGridButtonBoxPresenter.js, app/assets/javascripts/countries/presenters/show/CountryWidgetsModalPresenter.js, app/assets/javascripts/countries/router.js, app/assets/javascripts/countries/views/show/CountryGridButtonBoxView.js, app/assets/javascripts/countries/views/show/CountryWidgetsModalView.js, app/assets/stylesheets/modules/_form.scss, app/views/countries/show.html.erb
Fix customise indicators in footer button.
Allow going back with browser button on countries pages.
=> Country fixes

app/assets/javascripts/map/presenters/TabsPresenter.js, app/assets/javascripts/map/presenters/analysis/AnalysisResultsPresenter.js, app/assets/javascripts/map/templates/tabs.handlebars, app/assets/javascripts/map/views/TabsView.js, app/assets/stylesheets/modules/_buttons.scss, app/assets/stylesheets/modules/map/_module-tabs.scss
Add button to cancel an analysis
=> Feat: Cancel analysis request

app/assets/javascripts/countries/services/ReportService.js, app/assets/javascripts/countries/templates/countryReport.handlebars, app/assets/javascripts/countries/views/CountryReportView.js
Allow selecting primary forest and tree exclude options in the report section.
=> Allow to select primary forest and tree exclude

app/assets/javascripts/countries/services/CountryStatsService.js, app/assets/javascripts/countries/services/ReportService.js, app/assets/javascripts/insights/views/InsightsGladAlertsView.js
Fix query and update the .env variables with the /v1/ sufix.
=> Fix endpoints to new v1 API

Dockerfile, README.md, docker-compose-develop.yml, entrypoint.sh, gfw-climate.sh
* added docker files and updated readme
To test, run `./gfw-climate develop`
Further instructions added to README.md
=> Dockerised local app

app/assets/javascripts/map/cartocss/style.cartocss
Increased transparency of Land use polygons, and reduced line width of protected areas. 
Includes #394
=> Increased polygons transparency

app/assets/javascripts/map/views/LayersNavView.js, app/assets/javascripts/map/views/MapView.js, app/assets/stylesheets/layouts/_map.scss, app/views/shared/_header.html.slim, app/views/shared/_navbar2_landing.html.erb
=> Include menu on map page

app/views/shared/_transifex_setup.html.slim
=> update liveSettings assets

app/assets/javascripts/map/views/layers/BiomassLossLayer.js
* Biomass loss tiles updated to include 2016 data and new methodology
* Fix of a small logical comparison for issue #419
=> Updated biomass loss tiles

app/assets/javascripts/map/templates/layersNav.handlebars, app/assets/javascripts/map/views/LayersNavView.js, app/assets/javascripts/map/views/MapView.js, app/assets/javascripts/map/views/layers/SoilOrganicCarbonDLayer.js, app/views/layouts/map.html.slim
Include env variables to hide the new carbon layer in production.
```FEATURE_PANTROPICAL_DATA```
```FEATURE_CARBON_UPDATE```
=> Include feature flag for carbon layers and pantropical data

app/assets/javascripts/map/cartocss/uptake_pastures.cartocss, app/assets/javascripts/map/helpers/layersHelper.js, app/assets/javascripts/map/presenters/TimelinePresenter.js, app/assets/javascripts/map/templates/layersNav.handlebars, app/assets/javascripts/map/views/LegendView.js, app/assets/javascripts/map/views/layers/BiomassCarbonLayer.js, app/assets/javascripts/map/views/layers/UptakeTotal2028Layer.js, app/assets/javascripts/map/views/layers/UptakeTotal2038Layer.js, app/assets/javascripts/map/views/layers/UptakeTotal2048Layer.js, app/assets/javascripts/map/views/layers/UptakeTotalSGCarbonGainLayer.js
Adding the Total Carbon Gain layers as a different set of decadal gains per sub-layer.
=> Carbon gain layers

app/assets/javascripts/map/views/layers/BiomassLossLayer.js
Brings 2017 to the Biomass loss layer!
=> updated tiles to 2017 source

app/assets/javascripts/map/views/LegendView.js
Updates legend max values to those shown below:
=> updated legend values
